#! /usr/bin/perl

use Modern::Perl;
use Curses::UI;


# Create the root object.
my $cui = new Curses::UI ( 
    -clear_on_exit => 1, 
    -color_support  => 1,
);

# Demo index
my $current_demo = 1;

# Demo windows
my %w = ();

# ----------------------------------------------------------------------
# Create a menu
# ----------------------------------------------------------------------

sub select_page($;)
{
    my $nr = shift;
    $current_demo = $nr;
    $w{$current_demo}->focus;
}

my $menu_manage = [
    { -label => 'Show Feed',		-value	 => sub{select_page(3)}	},
    { -label => 'Add Feed',		-value	 => sub{select_page(1)}	},
    { -label => 'Delete Feed',		-value   => sub{select_page(2)}	},
    { -label => '-----------',		-value	 => sub{}		},
    { -label => 'Quit',			-value	 => sub{quit()}		},
];

my $menu = [
    { -label => 'Menu',			-submenu => $menu_manage	},
];

$cui->add('menu', 'Menubar', -menu => $menu);

# ----------------------------------------------------------------------
# Ceate the explanation window
# ----------------------------------------------------------------------

my $w0 = $cui->add(
    'w0', 'Window', 
    -border        => 1, 
    -y             => -1, 
    -height        => 3,
);
$w0->add('explain', 'Label', 
  -text => "CTRL+P: previous demo  CTRL+N: next demo  "
         . "CTRL+X: menu  CTRL+Q: quit"
);

# ----------------------------------------------------------------------
# Create the demo windows
# ----------------------------------------------------------------------

my %screens = (
    '1'  => 'Add Feed',
    '2'  => 'Delete Feed',
    '3'  => 'Show Feed',
);

my @screens = sort {$a<=>$b} keys %screens;

my %args = (
    -border       => 1, 
    -titlereverse => 0, 
    -padtop       => 2, 
    -padbottom    => 3, 
    -ipad         => 1,
);

while (my ($nr, $title) = each %screens)
{
    my $id = "window_$nr";
    $w{$nr} = $cui->add(
        $id, 'Window', 
        -title => $title,
        %args
    );
}

# ----------------------------------------------------------------------
#Add Feed
# ----------------------------------------------------------------------

$w{1}->add(undef, 'Label',
	   -border	=> 1,
	   -fg		=> 'blue',
	   -bfg		=> 'blue',
	   -text	=> "Here you can add feed. Just fill in\n"
			."the empty fields and press add =)",
	   -x		=> 15,
);

$w{1}->add('FeedNameText', 'TextEntry',
	   -fg		=> 'blue',
	   -x		=> 1,
	   -y		=> 7,
	   -width	=> 10,
	   -text	=> 'Feed Name',
	   -focusable	=> 0,
	   -readonly	=> 1,
);

my $FeedName = $w{1}->add('FeedName', 'TextEntry',
			  -border	=> 1,
			  -bfg		=> 'blue',
			  -x		=> 13,
			  -y		=> 6,
			  -width	=> 20,
);

$w{1}->add('FeedURLText', 'TextEntry',
	     -fg	=> 'blue',
	     -x		=> 1,
	     -y		=> 11,
	     -width	=> 10,
	     -text	=> 'Feed Url',
	     -focusable	=> 0,
	     -readonly	=> 1,
);

my $FeedUrl = $w{1}->add('FeedUrl', 'TextEntry',
			 -border	=> 1,
			 -bfg		=> 'blue',
			 -y		=> 10,
			 -x		=> 13,
			 -width		=> 20,
);

$w{1}->add('AddButton', 'Buttonbox',
	   -buttons	=> [ {-label	=> '< ADD >',
			      -onpress	=> \&add_feed } ],
	   -y		=> 15,
	   -x		=> 16,
);

# ----------------------------------------------------------------------
# Delete Feed
# ----------------------------------------------------------------------

$w{2}->add(undef, 'Label',
	   -border	=> 1,
	   -bfg		=> 'red',
	   -fg		=> 'red',
	   -x		=> 15,
	   -text	=> "Here You can delete feeds you don't want anymore\n"
			  ."To do so, just check the one you want to see removed and press < DEL >",
);

$w{2}->add(undef, 'Listbox',

# ----------------------------------------------------------------------
# Checkbox demo
# ----------------------------------------------------------------------

$w{3}->add(
    undef, 'Label',
    -text => "The checkbox can be used for selecting a true or false\n"
           . "value. If the checkbox is checked (a 'X' is inside it)\n"
           . "the value is true. <SPACE> and <ENTER> will toggle the\n"
           . "state of the checkbox, <Y> will check it and <N> will\n"
           . "uncheck it."
);

my $cb_no = "The checkbox says: I don't like it :-(";
my $cb_yes = "The checkbox says: I do like it! :-)";

$w{3}->add(
    'checkboxlabel', 'Label',
    -y       => 8,
    -width   => -1,
    -bold    => 1,
    -text    => "Check the checkbox please...",
);

$w{3}->add(
    undef, 'Checkbox',
    -y => 6,
    -checked => 0,
    -label => 'I like this Curses::UI demo so far!',
    -onchange => sub {
        my $cb = shift;
        my $label = $cb->parent->getobj('checkboxlabel'); 
        $label->text($cb->get ? $cb_yes : $cb_no);
    },
);


# ----------------------------------------------------------------------
# Setup bindings and focus 
# ----------------------------------------------------------------------

# Bind <CTRL+Q> to quit.
$cui->set_binding( sub{ exit }, "\cQ" );

# Bind <CTRL+X> to menubar.
$cui->set_binding( sub{ shift()->root->focus('menu') }, "\cX" );

sub goto_next_demo()
{
    $current_demo++;
    $current_demo = @screens if $current_demo > @screens;
    $w{$current_demo}->focus;
}
$cui->set_binding( \&goto_next_demo, "\cN" );

sub goto_prev_demo()
{
    $current_demo--;
    $current_demo = 1 if $current_demo < 1;
    $w{$current_demo}->focus;
}

$cui->set_binding( \&goto_prev_demo, "\cP" );

$w{$current_demo}->focus;


# ----------------------------------------------------------------------
# Get things rolling...
# ----------------------------------------------------------------------

$cui->mainloop;

